// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IContactsFields {
  /** Image */
  image: Asset;

  /** Text Block */
  textBlock: Document;

  /** Location */
  location: { lat: number; lon: number };

  /** Title */
  title: string;
}

/** Contacts section */

export interface IContacts extends Entry<IContactsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "contacts";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHomeFields {
  /** Title */
  title: string;

  /** Description */
  description: Document;

  /** Sub-title */
  subTitle: string;

  /** Main Image */
  mainImage?: Asset | undefined;

  /** External Text One */
  externalTextOne: string;

  /** Left Central Block */
  leftCentralBlock: Document;

  /** Right Central Block */
  rightCentralBlock: Document;

  /** External Text Two */
  externalTextTwo: string;
}

/** Home section */

export interface IHome extends Entry<IHomeFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "home";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "contacts" | "home";

export type IEntry = IContacts | IHome;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
