// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IAboutUsFields {
  /** Title */
  title: string;

  /** Main Image */
  mainImage: Asset;

  /** Description title */
  descriptionTitle: string;

  /** Description */
  description: Document;

  /** External Text */
  externalText: string;
}

/** In the middle of the page */

export interface IAboutUs extends Entry<IAboutUsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'aboutUs';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IArtistsFields {
  /** Title */
  artists: string;

  /** Artists Photos */
  artistsPhotos: Asset[];
}

export interface IArtists extends Entry<IArtistsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'artists';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IContactsFields {
  /** Image */
  image: Asset;

  /** Text Block */
  textBlock: Document;

  /** Location */
  location: { lat: number; lon: number };

  /** Title */
  title: string;
}

/** Contacts section */

export interface IContacts extends Entry<IContactsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'contacts';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IGalleryFields {
  /** Title */
  Title: string;

  /** Gallery */
  gallery: Asset[];
}

export interface IGallery extends Entry<IGalleryFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'gallery';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IHomeFields {
  /** Title */
  title: string;

  /** Description */
  description: Document;

  /** Sub-title */
  subTitle: string;

  /** Main Image */
  mainImage?: Asset | undefined;

  /** External Text One */
  externalTextOne: string;

  /** Left Central Block Title */
  leftCentralBlockTitle?: string | undefined;

  /** Left Central Block */
  leftCentralBlock: Document;

  /** Right Central Block Title */
  rightCentralBlockTitle: string;

  /** Right Central Block */
  rightCentralBlock: Document;

  /** External Text Two */
  externalTextTwo: string;

  /** Second description title */
  secondDescriptionTitle: string;

  /** Second description */
  secondDescription: Document;

  /** Second Image */
  secondImage: Asset;
}

/** Home section */

export interface IHome extends Entry<IHomeFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'home';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILogoFields {
  /** Title */
  title: string;

  /** Logo */
  logo: Asset;
}

/** Logo content */

export interface ILogo extends Entry<ILogoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'logo';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'aboutUs' | 'artists' | 'contacts' | 'gallery' | 'home' | 'logo';

export type IEntry = IAboutUs | IArtists | IContacts | IGallery | IHome | ILogo;

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
